In [ ]:
import pandas as pd

file_path1 = r"C:\\Users\\kanam\\OneDrive\\Documents\\project\\PhysioNet2019\\combined_training_data.psv";

df = pd.read_csv(file_path1, sep=",")

print("Dataset Shape:", df.shape)
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

display(df.head())

Dataset Shape: (1552210, 43)
Total Rows: 1552210
Total Columns: 43

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID,Dataset
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,83.14,0,NaN,NaN,-0.03,1,0,p000001,A
1,97.0,95.0,NaN,98.0,75.33,NaN,19.0,NaN,NaN,NaN,...,NaN,83.14,0,NaN,NaN,-0.03,2,0,p000001,A
2,89.0,99.0,NaN,122.0,86.00,NaN,22.0,NaN,NaN,NaN,...,NaN,83.14,0,NaN,NaN,-0.03,3,0,p000001,A
3,90.0,95.0,NaN,NaN,NaN,NaN,30.0,NaN,24.0,NaN,...,NaN,83.14,0,NaN,NaN,-0.03,4,0,p000001,A
4,103.0,88.5,NaN,122.0,91.33,NaN,24.5,NaN,NaN,NaN,...,NaN,83.14,0,NaN,NaN,-0.03,5,0,p000001,A

In [ ]:
print(df.columns.tolist())

['HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP', 'Resp', 'EtCO2', 'BaseExcess', 'HCO3', 'FiO2', 'pH', 'PaCO2', 'SaO2', 'AST', 'BUN', 'Alkalinephos', 'Calcium', 'Chloride', 'Creatinine', 'Bilirubin_direct', 'Glucose', 'Lactate', 'Magnesium', 'Phosphate', 'Potassium', 'Bilirubin_total', 'TroponinI', 'Hct', 'Hgb', 'PTT', 'WBC', 'Fibrinogen', 'Platelets', 'Age', 'Gender', 'Unit1', 'Unit2', 'HospAdmTime', 'ICULOS', 'SepsisLabel', 'Patient_ID', 'Dataset']

In [ ]:
print(df["Dataset"].unique())

print("\nDataset value counts:")
print(df["Dataset"].value_counts())

<StringArray>
['A', 'B']
Length: 2, dtype: str

Dataset value counts:
Dataset
A    790215
B    761995
Name: count, dtype: int64

In [ ]:
df = df.drop(columns=["Dataset"])

print(df.columns.tolist())
print("Updated Dataset Shape:", df.shape)

['HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP', 'Resp', 'EtCO2', 'BaseExcess', 'HCO3', 'FiO2', 'pH', 'PaCO2', 'SaO2', 'AST', 'BUN', 'Alkalinephos', 'Calcium', 'Chloride', 'Creatinine', 'Bilirubin_direct', 'Glucose', 'Lactate', 'Magnesium', 'Phosphate', 'Potassium', 'Bilirubin_total', 'TroponinI', 'Hct', 'Hgb', 'PTT', 'WBC', 'Fibrinogen', 'Platelets', 'Age', 'Gender', 'Unit1', 'Unit2', 'HospAdmTime', 'ICULOS', 'SepsisLabel', 'Patient_ID']
Updated Dataset Shape: (1552210, 42)

In [ ]:
df_copy = df.copy(deep=True)

In [ ]:
df_copy.shape

(1552210, 42)

In [ ]:
display(df_copy.head())

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,83.14,0,NaN,NaN,-0.03,1,0,p000001
1,97.0,95.0,NaN,98.0,75.33,NaN,19.0,NaN,NaN,NaN,...,NaN,NaN,83.14,0,NaN,NaN,-0.03,2,0,p000001
2,89.0,99.0,NaN,122.0,86.00,NaN,22.0,NaN,NaN,NaN,...,NaN,NaN,83.14,0,NaN,NaN,-0.03,3,0,p000001
3,90.0,95.0,NaN,NaN,NaN,NaN,30.0,NaN,24.0,NaN,...,NaN,NaN,83.14,0,NaN,NaN,-0.03,4,0,p000001
4,103.0,88.5,NaN,122.0,91.33,NaN,24.5,NaN,NaN,NaN,...,NaN,NaN,83.14,0,NaN,NaN,-0.03,5,0,p000001

In [ ]:
print(df.describe());

                 HR         O2Sat           Temp           SBP           MAP  \
count  1.398811e+06  1.349474e+06  525226.000000  1.325945e+06  1.358940e+06
mean   8.458144e+01  9.719395e+01      36.977228  1.237505e+02  8.240010e+01
std    1.732524e+01  2.936924e+00       0.770014  2.323156e+01  1.634175e+01
min    2.000000e+01  2.000000e+01      20.900000  2.000000e+01  2.000000e+01
25%    7.200000e+01  9.600000e+01      36.500000  1.070000e+02  7.100000e+01
50%    8.350000e+01  9.800000e+01      37.000000  1.210000e+02  8.000000e+01
75%    9.550000e+01  9.950000e+01      37.500000  1.380000e+02  9.200000e+01
max    2.800000e+02  1.000000e+02      50.000000  3.000000e+02  3.000000e+02

                DBP          Resp         EtCO2    BaseExcess          HCO3  \
count  1.065656e+06  1.313875e+06  57636.000000  84145.000000  65028.000000
mean   6.383056e+01  1.872650e+01     32.957657     -0.689919     24.075481
std    1.395601e+01  5.098194e+00      7.951662      4.294297      4.376504
min    2.000000e+01  1.000000e+00     10.000000    -32.000000      0.000000
25%    5.400000e+01  1.500000e+01     28.000000     -3.000000     22.000000
50%    6.200000e+01  1.800000e+01     33.000000      0.000000     24.000000
75%    7.200000e+01  2.150000e+01     38.000000      1.000000     26.800000
max    3.000000e+02  1.000000e+02    100.000000    100.000000     55.000000

       ...           WBC    Fibrinogen     Platelets           Age  \
count  ...  99447.000000  10242.000000  92209.000000  1.552210e+06
mean   ...     11.446405    287.385706    196.013911  6.200947e+01
std    ...      7.731013    153.002908    103.635366  1.638622e+01
min    ...      0.100000     34.000000      1.000000  1.400000e+01
25%    ...      7.600000    184.000000    126.000000  5.168000e+01
50%    ...     10.300000    250.000000    181.000000  6.400000e+01
75%    ...     13.800000    349.000000    244.000000  7.400000e+01
max    ...    440.000000   1760.000000   2322.000000  1.000000e+02

             Gender          Unit1          Unit2   HospAdmTime        ICULOS  \
count  1.552210e+06  940250.000000  940250.000000  1.552202e+06  1.552210e+06
mean   5.592690e-01       0.496571       0.503429 -5.612512e+01  2.699499e+01
std    4.964749e-01       0.499989       0.499989  1.622569e+02  2.900542e+01
min    0.000000e+00       0.000000       0.000000 -5.366860e+03  1.000000e+00
25%    0.000000e+00       0.000000       0.000000 -4.705000e+01  1.100000e+01
50%    1.000000e+00       0.000000       1.000000 -6.030000e+00  2.100000e+01
75%    1.000000e+00       1.000000       1.000000 -4.000000e-02  3.400000e+01
max    1.000000e+00       1.000000       1.000000  2.399000e+01  3.360000e+02

        SepsisLabel
count  1.552210e+06
mean   1.798468e-02
std    1.328956e-01
min    0.000000e+00
25%    0.000000e+00
50%    0.000000e+00
75%    0.000000e+00
max    1.000000e+00

[8 rows x 41 columns]

In [ ]:
missing_values = df_copy.isnull().sum()
print("Missing Values per Column:")
print(missing_values)

Missing Values per Column:
HR                   153399
O2Sat                202736
Temp                1026984
SBP                  226265
MAP                  193270
DBP                  486554
Resp                 238335
EtCO2               1494574
BaseExcess          1468065
HCO3                1487182
FiO2                1422845
pH                  1444637
PaCO2               1465909
SaO2                1498649
AST                 1527027
BUN                 1445642
Alkalinephos        1527269
Calcium             1460879
Chloride            1481744
Creatinine          1457594
Bilirubin_direct    1549220
Glucose             1286694
Lactate             1510764
Magnesium           1454259
Phosphate           1489909
Potassium           1407685
Bilirubin_total     1529069
TroponinI           1537429
Hct                 1414777
Hgb                 1437619
PTT                 1506511
WBC                 1452763
Fibrinogen          1541968
Platelets           1460001
Age                       0
Gender                    0
Unit1                611960
Unit2                611960
HospAdmTime               8
ICULOS                    0
SepsisLabel               0
Patient_ID                0
dtype: int64

In [ ]:
df_copy = df_copy.drop_duplicates()
print(df_copy.shape)
print(df_copy.duplicated().sum())

(1552210, 42)
0

In [ ]:
import pandas as pd
from sklearn.impute import SimpleImputer

df_clean = df_copy.copy(deep=True)

df_clean = df_clean.sort_values(
    ["Patient_ID", "ICULOS"]
).reset_index(drop=True)

numerical_cols = [
    col for col in df_clean.select_dtypes(include="number").columns
    if col != "SepsisLabel"
]

df_clean[numerical_cols] = (
    df_clean.groupby("Patient_ID")[numerical_cols].ffill()
)

imputer = SimpleImputer(strategy="median")
df_clean[numerical_cols] = imputer.fit_transform(
    df_clean[numerical_cols]
)

print("Total missing values:", df_clean.isnull().sum().sum())
print("Dataset shape:", df_clean.shape)

display(df_clean.head())

Total missing values: 0
Dataset shape: (1552210, 42)

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,83.0,98.0,36.83,121.0,81.00,62.0,18.0,34.0,0.0,24.0,...,264.0,190.0,83.14,0.0,0.0,1.0,-0.03,1.0,0,p000001
1,97.0,95.0,36.83,98.0,75.33,62.0,19.0,34.0,0.0,24.0,...,264.0,190.0,83.14,0.0,0.0,1.0,-0.03,2.0,0,p000001
2,89.0,99.0,36.83,122.0,86.00,62.0,22.0,34.0,0.0,24.0,...,264.0,190.0,83.14,0.0,0.0,1.0,-0.03,3.0,0,p000001
3,90.0,95.0,36.83,122.0,86.00,62.0,30.0,34.0,24.0,24.0,...,264.0,190.0,83.14,0.0,0.0,1.0,-0.03,4.0,0,p000001
4,103.0,88.5,36.83,122.0,91.33,62.0,24.5,34.0,24.0,24.0,...,264.0,190.0,83.14,0.0,0.0,1.0,-0.03,5.0,0,p000001

In [ ]:
print(df_clean["SepsisLabel"].value_counts())
print("\nTarget percentages:")
print(df_clean["SepsisLabel"].value_counts(normalize=True) * 100)

SepsisLabel
0    1524294
1      27916
Name: count, dtype: int64

Target percentages:
SepsisLabel
0    98.201532
1     1.798468
Name: proportion, dtype: float64

In [ ]:
from sklearn.model_selection import GroupShuffleSplit

drop_cols = ["SepsisLabel", "Patient_ID"]

X = df_clean.drop(
    columns=[col for col in drop_cols if col in df_clean.columns]
)
y = df_clean["SepsisLabel"]
groups = df_clean["Patient_ID"]

split1 = GroupShuffleSplit(
    n_splits=1,
    test_size=0.30,
    random_state=42
)

train_idx, temp_idx = next(split1.split(X, y, groups=groups))

X_temp = X.iloc[temp_idx]
y_temp = y.iloc[temp_idx]
groups_temp = groups.iloc[temp_idx]

split2 = GroupShuffleSplit(
    n_splits=1,
    test_size=0.50,
    random_state=42
)

val_rel_idx, test_rel_idx = next(
    split2.split(X_temp, y_temp, groups=groups_temp)
)

val_idx = temp_idx[val_rel_idx]
test_idx = temp_idx[test_rel_idx]

X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]
X_test, y_test = X.iloc[test_idx], y.iloc[test_idx]

print("Training:", X_train.shape, y_train.shape)
print("Validation:", X_val.shape, y_val.shape)
print("Testing:", X_test.shape, y_test.shape)

train_patients = set(groups.iloc[train_idx])
val_patients = set(groups.iloc[val_idx])
test_patients = set(groups.iloc[test_idx])

print("Train-validation overlap:", len(train_patients & val_patients))
print("Train-test overlap:", len(train_patients & test_patients))
print("Validation-test overlap:", len(val_patients & test_patients))

Training: (1087702, 40) (1087702,)
Validation: (233793, 40) (233793,)
Testing: (230715, 40) (230715,)
Train-validation overlap: 0
Train-test overlap: 0
Validation-test overlap: 0

In [ ]:
print("Training labels:")
print(y_train.value_counts())

print("\nValidation labels:")
print(y_val.value_counts())

print("\nTesting labels:")
print(y_test.value_counts())

Training labels:
SepsisLabel
0    1067857
1      19845
Name: count, dtype: int64

Validation labels:
SepsisLabel
0    229621
1      4172
Name: count, dtype: int64

Testing labels:
SepsisLabel
0    226816
1      3899
Name: count, dtype: int64

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import (
    classification_report,
    average_precision_score,
    roc_auc_score
)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
scale_weight = neg / pos

print("Scale positive weight:", scale_weight)

xgb_model = XGBClassifier(
    n_estimators=600,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_weight,
    eval_metric="aucpr",
    random_state=42,
    n_jobs=-1
)

# Train model
xgb_model.fit(
    X_train,
    y_train,
    eval_set=[(X_val, y_val)],
    verbose=50
)

y_val_prob = xgb_model.predict_proba(X_val)[:, 1]
y_val_pred = (y_val_prob >= 0.5).astype(int)

print("\nValidation Classification Report:")
print(classification_report(y_val, y_val_pred, zero_division=0))

print("Validation AUPRC:", average_precision_score(y_val, y_val_prob))
print("Validation ROC-AUC:", roc_auc_score(y_val, y_val_prob))

Scale positive weight: 53.809876543209874
[0]	validation_0-aucpr:0.04091
[50]	validation_0-aucpr:0.09790
[100]	validation_0-aucpr:0.10329
[150]	validation_0-aucpr:0.10388
[200]	validation_0-aucpr:0.10366
[250]	validation_0-aucpr:0.10315
[300]	validation_0-aucpr:0.10200
[350]	validation_0-aucpr:0.10257
[400]	validation_0-aucpr:0.10245
[450]	validation_0-aucpr:0.10145
[500]	validation_0-aucpr:0.10065
[550]	validation_0-aucpr:0.10108
[599]	validation_0-aucpr:0.10045

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.84      0.91    229621
           1       0.07      0.64      0.12      4172

    accuracy                           0.84    233793
   macro avg       0.53      0.74      0.52    233793
weighted avg       0.98      0.84      0.90    233793

Validation AUPRC: 0.10062024744575973
Validation ROC-AUC: 0.8232775648278118

In [ ]:
import pandas as pd
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import average_precision_score
from xgboost import XGBClassifier

param_grid = {
    "max_depth": [3, 4, 5],
    "learning_rate": [0.03, 0.05],
    "min_child_weight": [1, 5]
}

results = []
best_model = None
best_auprc = -1
best_params = None

for params in ParameterGrid(param_grid):

    model = XGBClassifier(
        n_estimators=1000,
        max_depth=params["max_depth"],
        learning_rate=params["learning_rate"],
        min_child_weight=params["min_child_weight"],
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_weight,
        eval_metric="aucpr",
        early_stopping_rounds=50,
        random_state=42,
        n_jobs=-1,
        tree_method="hist"
    )

    model.fit(
        X_train,
        y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )

    val_prob = model.predict_proba(X_val)[:, 1]
    val_auprc = average_precision_score(y_val, val_prob)

    results.append({
        **params,
        "Best_iteration": model.best_iteration,
        "Validation_AUPRC": val_auprc
    })

    print(
        f"Parameters: {params} | "
        f"Best iteration: {model.best_iteration} | "
        f"Validation AUPRC: {val_auprc:.5f}"
    )

    if val_auprc > best_auprc:
        best_auprc = val_auprc
        best_model = model
        best_params = params

results_df = pd.DataFrame(results).sort_values(
    "Validation_AUPRC", ascending=False
)

print("\nBest Hyperparameters:", best_params)
print("Best Validation AUPRC:", round(best_auprc, 5))
print("Best Boosting Iteration:", best_model.best_iteration)

display(results_df)

model_path = r"C:\Users\kanam\OneDrive\Documents\project\PhysioNet2019\xgboost_tuned_model.pkl"

joblib.dump(best_model, model_path)

print("Best model saved successfully!")
print("Saved at:", model_path)

Parameters: {'learning_rate': 0.03, 'max_depth': 3, 'min_child_weight': 1} | Best iteration: 224 | Validation AUPRC: 0.10483
Parameters: {'learning_rate': 0.03, 'max_depth': 3, 'min_child_weight': 5} | Best iteration: 224 | Validation AUPRC: 0.10483
Parameters: {'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 1} | Best iteration: 245 | Validation AUPRC: 0.10604
Parameters: {'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 5} | Best iteration: 303 | Validation AUPRC: 0.10653
Parameters: {'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 1} | Best iteration: 100 | Validation AUPRC: 0.10348
Parameters: {'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 5} | Best iteration: 175 | Validation AUPRC: 0.10405
Parameters: {'learning_rate': 0.05, 'max_depth': 3, 'min_child_weight': 1} | Best iteration: 195 | Validation AUPRC: 0.10561
Parameters: {'learning_rate': 0.05, 'max_depth': 3, 'min_child_weight': 5} | Best iteration: 195 | Validation AUPRC: 0.10561
Parameters: {'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 1} | Best iteration: 110 | Validation AUPRC: 0.10447
Parameters: {'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 5} | Best iteration: 110 | Validation AUPRC: 0.10447
Parameters: {'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 1} | Best iteration: 76 | Validation AUPRC: 0.10361
Parameters: {'learning_rate': 0.05, 'max_depth': 5, 'min_child_weight': 5} | Best iteration: 76 | Validation AUPRC: 0.10359

Best Hyperparameters: {'learning_rate': 0.03, 'max_depth': 4, 'min_child_weight': 5}
Best Validation AUPRC: 0.10653
Best Boosting Iteration: 303

,learning_rate,max_depth,min_child_weight,Best_iteration,Validation_AUPRC
3,0.03,4,5,303,0.106526
2,0.03,4,1,245,0.106038
7,0.05,3,5,195,0.105612
6,0.05,3,1,195,0.105612
0,0.03,3,1,224,0.104829
1,0.03,3,5,224,0.104829
9,0.05,4,5,110,0.104475
8,0.05,4,1,110,0.104474
5,0.03,5,5,175,0.104047
10,0.05,5,1,76,0.103614
11,0.05,5,5,76,0.103588
4,0.03,5,1,100,0.103483

Best model saved successfully!
Saved at: C:\Users\kanam\OneDrive\Documents\project\PhysioNet2019\xgboost_tuned_model.pkl

In [ ]:
import numpy as np
from sklearn.metrics import precision_recall_curve

val_prob = best_model.predict_proba(X_val)[:, 1]

precision, recall, thresholds = precision_recall_curve(
    y_val, val_prob
)

f1_scores = (
    2 * precision[:-1] * recall[:-1] /
    (precision[:-1] + recall[:-1] + 1e-12)
)

best_idx = np.argmax(f1_scores)
best_threshold = thresholds[best_idx]

print("Best threshold:", best_threshold)
print("Validation precision:", precision[best_idx])
print("Validation recall:", recall[best_idx])
print("Validation F1-score:", f1_scores[best_idx])

Best threshold: 0.80542177
Validation precision: 0.13560056319722733
Validation recall: 0.3000958772770853
Validation F1-score: 0.18679597165193976

In [ ]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    average_precision_score,
    roc_auc_score
)

y_test_prob = best_model.predict_proba(X_test)[:, 1]

best_threshold = 0.80542177
y_test_pred = (y_test_prob >= best_threshold).astype(int)

print("Test Average Precision (AUPRC):",
      average_precision_score(y_test, y_test_prob))

print("Test ROC-AUC:",
      roc_auc_score(y_test, y_test_prob))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred, zero_division=0))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

Test Average Precision (AUPRC): 0.09672835916441072
Test ROC-AUC: 0.8254477341548623

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.96      0.98    226816
           1       0.13      0.30      0.18      3899

    accuracy                           0.95    230715
   macro avg       0.56      0.63      0.58    230715
weighted avg       0.97      0.95      0.96    230715


Confusion Matrix:
[[218567   8249]
 [  2713   1186]]

In [ ]:
from sklearn.metrics import (
    average_precision_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

models = {
    "Base XGBoost": (xgb_model, 0.5),
    "Tuned XGBoost": (best_model, 0.80542177)
}

for name, (model, threshold) in models.items():
    y_prob = model.predict_proba(X_test)[:, 1]
    y_pred = (y_prob >= threshold).astype(int)

    print(f"\n{'=' * 50}")
    print(name)
    print("Threshold:", threshold)
    print("Test AUPRC:", average_precision_score(y_test, y_prob))
    print("Test ROC-AUC:", roc_auc_score(y_test, y_prob))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, zero_division=0))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

==================================================
Base XGBoost
Threshold: 0.5
Test AUPRC: 0.09105370906074507
Test ROC-AUC: 0.8229463913239676

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.84      0.91    226816
           1       0.06      0.63      0.12      3899

    accuracy                           0.84    230715
   macro avg       0.53      0.74      0.51    230715
weighted avg       0.98      0.84      0.90    230715

Confusion Matrix:
[[191100  35716]
 [  1425   2474]]

==================================================
Tuned XGBoost
Threshold: 0.80542177
Test AUPRC: 0.09672835916441072
Test ROC-AUC: 0.8254477341548623

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.96      0.98    226816
           1       0.13      0.30      0.18      3899

    accuracy                           0.95    230715
   macro avg       0.56      0.63      0.58    230715
weighted avg       0.97      0.95      0.96    230715

Confusion Matrix:
[[218567   8249]
 [  2713   1186]]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

train_ids = df_clean.loc[X_train.index, "Patient_ID"]
val_ids = df_clean.loc[X_val.index, "Patient_ID"]
test_ids = df_clean.loc[X_test.index, "Patient_ID"]

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train).astype(np.float32)
X_val_scaled = scaler.transform(X_val).astype(np.float32)
X_test_scaled = scaler.transform(X_test).astype(np.float32)

print("Train:", X_train_scaled.shape)
print("Validation:", X_val_scaled.shape)
print("Test:", X_test_scaled.shape)

Train: (1087702, 40)
Validation: (233793, 40)
Test: (230715, 40)

In [ ]:
def create_sequences(X, y, patient_ids, icu_hours,
                     seq_length=12, stride=6):

    X_seq, y_seq = [], []

    data = pd.DataFrame({
        "patient_id": patient_ids.to_numpy(),
        "icu_hours": icu_hours.to_numpy(),
        "label": y.to_numpy(),
        "position": np.arange(len(X))
    })

    for _, group in data.groupby("patient_id", sort=False):
        group = group.sort_values("icu_hours")
        positions = group["position"].to_numpy()
        labels = group["label"].to_numpy()

        for end in range(seq_length - 1, len(group), stride):
            start = end - seq_length + 1
            window_positions = positions[start:end + 1]

            hours = group["icu_hours"].to_numpy()[start:end + 1]
            if len(hours) != seq_length or np.any(np.diff(hours) != 1):
                continue

            X_seq.append(X[window_positions])
            y_seq.append(labels[end])

    return np.asarray(X_seq, dtype=np.float32), np.asarray(y_seq, dtype=np.int32)


train_hours = df_clean.loc[X_train.index, "ICULOS"]
val_hours = df_clean.loc[X_val.index, "ICULOS"]
test_hours = df_clean.loc[X_test.index, "ICULOS"]

X_train_seq, y_train_seq = create_sequences(
    X_train_scaled, y_train, train_ids, train_hours
)

X_val_seq, y_val_seq = create_sequences(
    X_val_scaled, y_val, val_ids, val_hours
)

X_test_seq, y_test_seq = create_sequences(
    X_test_scaled, y_test, test_ids, test_hours
)

print("Training sequences:", X_train_seq.shape, y_train_seq.shape)
print("Validation sequences:", X_val_seq.shape, y_val_seq.shape)
print("Test sequences:", X_test_seq.shape, y_test_seq.shape)

print("Training positive rate:", y_train_seq.mean())
print("Validation positive rate:", y_val_seq.mean())
print("Test positive rate:", y_test_seq.mean())

Training sequences: (141402, 12, 40) (141402,)
Validation sequences: (30452, 12, 40) (30452,)
Test sequences: (29863, 12, 40) (29863,)
Training positive rate: 0.018790399004257365
Validation positive rate: 0.0188821752265861
Test positive rate: 0.016408264407460738

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.utils.class_weight import compute_class_weight

tf.keras.utils.set_random_seed(42)

classes = np.unique(y_train_seq)

weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_train_seq
)

class_weights = dict(zip(classes, weights))

print("Class weights:", class_weights)

model = Sequential([
    Input(shape=(X_train_seq.shape[1], X_train_seq.shape[2])),
    LSTM(64, return_sequences=True),
    Dropout(0.3),
    LSTM(32),
    Dropout(0.3),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.AUC(curve="PR", name="auprc"),
        tf.keras.metrics.AUC(curve="ROC", name="roc_auc"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

callbacks = [
    EarlyStopping(
        monitor="val_auprc",
        mode="max",
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor="val_auprc",
        mode="max",
        factor=0.5,
        patience=2,
        min_lr=1e-6,
        verbose=1
    )
]

history = model.fit(
    X_train_seq,
    y_train_seq,
    validation_data=(X_val_seq, y_val_seq),
    epochs=40,
    batch_size=256,
    class_weight=class_weights,
    callbacks=callbacks,
    verbose=1
)

Class weights: {np.int32(0): np.float64(0.5095751198241378), np.int32(1): np.float64(26.609333835152427)}
WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 17s 25ms/step - auprc: 0.0709 - loss: 0.5829 - recall: 0.6632 - roc_auc: 0.7601 - val_auprc: 0.0899 - val_loss: 0.5607 - val_recall: 0.6678 - val_roc_auc: 0.7972 - learning_rate: 0.0010
Epoch 2/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 13s 23ms/step - auprc: 0.0880 - loss: 0.5314 - recall: 0.7068 - roc_auc: 0.8109 - val_auprc: 0.0991 - val_loss: 0.5344 - val_recall: 0.6870 - val_roc_auc: 0.7981 - learning_rate: 0.0010
Epoch 3/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 12s 23ms/step - auprc: 0.0997 - loss: 0.4970 - recall: 0.7478 - roc_auc: 0.8389 - val_auprc: 0.0965 - val_loss: 0.4865 - val_recall: 0.6522 - val_roc_auc: 0.7924 - learning_rate: 0.0010
Epoch 4/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - auprc: 0.1139 - loss: 0.4637 - recall: 0.7881 - roc_auc: 0.8623
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
553/553 ━━━━━━━━━━━━━━━━━━━━ 13s 23ms/step - auprc: 0.1139 - loss: 0.4637 - recall: 0.7881 - roc_auc: 0.8623 - val_auprc: 0.0917 - val_loss: 0.4825 - val_recall: 0.6348 - val_roc_auc: 0.7781 - learning_rate: 0.0010
Epoch 5/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 12s 22ms/step - auprc: 0.1284 - loss: 0.4202 - recall: 0.8231 - roc_auc: 0.8869 - val_auprc: 0.0894 - val_loss: 0.4622 - val_recall: 0.6226 - val_roc_auc: 0.7703 - learning_rate: 5.0000e-04
Epoch 6/40
551/553 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - auprc: 0.1460 - loss: 0.3927 - recall: 0.8516 - roc_auc: 0.9010
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
553/553 ━━━━━━━━━━━━━━━━━━━━ 12s 22ms/step - auprc: 0.1460 - loss: 0.3923 - recall: 0.8517 - roc_auc: 0.9010 - val_auprc: 0.0845 - val_loss: 0.4443 - val_recall: 0.6348 - val_roc_auc: 0.7660 - learning_rate: 5.0000e-04
Epoch 7/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 12s 22ms/step - auprc: 0.1666 - loss: 0.3612 - recall: 0.8743 - roc_auc: 0.9156 - val_auprc: 0.0783 - val_loss: 0.4099 - val_recall: 0.5965 - val_roc_auc: 0.7588 - learning_rate: 2.5000e-04
Epoch 7: early stopping
Restoring model weights from the end of the best epoch: 2.

In [ ]:

history_continue = model.fit(
    X_train_seq,
    y_train_seq,
    validation_data=(X_val_seq, y_val_seq),
    initial_epoch=7,
    epochs=40,
    batch_size=256,
    class_weight=class_weights,
    callbacks=callbacks,
    verbose=1
)

Epoch 8/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 14s 25ms/step - auprc: 0.1032 - loss: 0.4804 - recall: 0.7644 - roc_auc: 0.8513 - val_auprc: 0.1018 - val_loss: 0.4672 - val_recall: 0.6435 - val_roc_auc: 0.7959 - learning_rate: 2.5000e-04
Epoch 9/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 14s 24ms/step - auprc: 0.1095 - loss: 0.4669 - recall: 0.7802 - roc_auc: 0.8599 - val_auprc: 0.1037 - val_loss: 0.4637 - val_recall: 0.6557 - val_roc_auc: 0.7934 - learning_rate: 2.5000e-04
Epoch 10/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 15s 27ms/step - auprc: 0.1147 - loss: 0.4556 - recall: 0.7889 - roc_auc: 0.8673 - val_auprc: 0.1039 - val_loss: 0.4665 - val_recall: 0.6574 - val_roc_auc: 0.7875 - learning_rate: 2.5000e-04
Epoch 11/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 15s 28ms/step - auprc: 0.1224 - loss: 0.4423 - recall: 0.8062 - roc_auc: 0.8752 - val_auprc: 0.0976 - val_loss: 0.4581 - val_recall: 0.6522 - val_roc_auc: 0.7842 - learning_rate: 2.5000e-04
Epoch 12/40
551/553 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - auprc: 0.1234 - loss: 0.4283 - recall: 0.8218 - roc_auc: 0.8828
Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
553/553 ━━━━━━━━━━━━━━━━━━━━ 22s 30ms/step - auprc: 0.1234 - loss: 0.4278 - recall: 0.8220 - roc_auc: 0.8829 - val_auprc: 0.0938 - val_loss: 0.4594 - val_recall: 0.6296 - val_roc_auc: 0.7750 - learning_rate: 2.5000e-04
Epoch 13/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 15s 27ms/step - auprc: 0.1356 - loss: 0.4072 - recall: 0.8382 - roc_auc: 0.8939 - val_auprc: 0.0945 - val_loss: 0.4268 - val_recall: 0.6139 - val_roc_auc: 0.7718 - learning_rate: 1.2500e-04
Epoch 14/40
552/553 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - auprc: 0.1320 - loss: 0.4025 - recall: 0.8453 - roc_auc: 0.8962
Epoch 14: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
553/553 ━━━━━━━━━━━━━━━━━━━━ 16s 28ms/step - auprc: 0.1319 - loss: 0.4024 - recall: 0.8453 - roc_auc: 0.8962 - val_auprc: 0.0909 - val_loss: 0.4165 - val_recall: 0.5983 - val_roc_auc: 0.7664 - learning_rate: 1.2500e-04
Epoch 15/40
553/553 ━━━━━━━━━━━━━━━━━━━━ 15s 27ms/step - auprc: 0.1380 - loss: 0.3979 - recall: 0.8502 - roc_auc: 0.8983 - val_auprc: 0.0899 - val_loss: 0.4114 - val_recall: 0.5965 - val_roc_auc: 0.7663 - learning_rate: 6.2500e-05
Epoch 15: early stopping
Restoring model weights from the end of the best epoch: 10.

In [ ]:
import joblib
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    average_precision_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)




y_test_prob = model.predict(X_test_seq, verbose=1).ravel()
y_test_pred = (y_test_prob >= 0.5).astype(int)

print("\n========== LSTM TEST RESULTS ==========")
print(f"Accuracy:  {accuracy_score(y_test_seq, y_test_pred):.4f}")
print(f"Precision: {precision_score(y_test_seq, y_test_pred, zero_division=0):.4f}")
print(f"Recall:    {recall_score(y_test_seq, y_test_pred, zero_division=0):.4f}")
print(f"F1-score:  {f1_score(y_test_seq, y_test_pred, zero_division=0):.4f}")
print(f"AUPRC:     {average_precision_score(y_test_seq, y_test_prob):.4f}")
print(f"ROC-AUC:   {roc_auc_score(y_test_seq, y_test_prob):.4f}")

print("\nClassification Report:")
print(classification_report(
    y_test_seq,
    y_test_pred,
    target_names=["Non-Sepsis", "Sepsis"],
    zero_division=0
))

print("Confusion Matrix:")
print(confusion_matrix(y_test_seq, y_test_pred))

934/934 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step

========== LSTM TEST RESULTS ==========
Accuracy:  0.7955
Precision: 0.0526
Recall:    0.6735
F1-score:  0.0975
AUPRC:     0.0851
ROC-AUC:   0.8128

Classification Report:
              precision    recall  f1-score   support

  Non-Sepsis       0.99      0.80      0.88     29373
      Sepsis       0.05      0.67      0.10       490

    accuracy                           0.80     29863
   macro avg       0.52      0.74      0.49     29863
weighted avg       0.98      0.80      0.87     29863

Confusion Matrix:
[[23425  5948]
 [  160   330]]